// layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppProviders } from "@/components/AppProviders";
import TwoCellComponent from "@/components/Fila1";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gasodomesticos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          "min-h-screen bg-background font-sans antialiased flex items-center justify-center" +
          inter.className
        }
      >
        <AppProviders>
       
          {children}
        </AppProviders>
      </body>
    </html>
  );
}
